enableRobotsTXT = true
canonifyURLs = true
baseURL = "https://www.nfrba.co.uk/"
title = "North Foreland Regional Badminton Association"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true